services:
  - type: web
    name: tongues
    env: python
    region: oregon
    branch: main
    runtime: python-3.12.0
    buildCommand: |
      pip install --upgrade pip
      pip install --no-cache-dir numpy scipy
      pip install -r requirements.txt
    startCommand: python -m shiny run app.py --host 0.0.0.0 --port $PORT
    autoDeploy: true