services:
  - type: web
    name: tongues
    env: python
    region: oregon
    branch: main
    buildCommand: |
      apt-get update
      apt-get install -y gfortran libopenblas-dev
      pip install --upgrade pip
      pip install --no-cache-dir -r requirements.txt
    startCommand: python -m shiny run app.py --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.12"
    autoDeploy: true